### ISSUE TITLE
Undefined function

### ISSUE THREAD

**Issue by Syqinx** [snap-research/graphless-neural-networks#13]
There is an undefined function in your code(dataloader.py, line 257, rand_train_test_idx). I can't find the function from your code and imported packages. What is this?

**Comment by ShichangZh** [comment]
Thank you for catching it. This is a legacy code that we used to test random splits of input data. It is not used in the experiments. Please refer to https://github.com/snap-research/graphless-neural-networks/blob/76da5d1b5d8258d5ea9ae7d4fa63f6a20a47c27c/utils.py#L103 for the updated split function.

**Comment by Syqinx** [comment]
Thank you for your quick reply. It's very helpful for me!
