### ISSUE TITLE
 Failed to build environment

### ISSUE THREAD

**Issue by 404creep** [snap-research/graphless-neural-networks#5]
the packages in requirement.txt is incomplete , and fail to use bash ./prepare_env.sh to  install some packages

**Comment by ShichangZh** [comment]
Sorry for the late reply. I didn't get an email notification for this new issue. Could you please let me know which package was missing? It is better if you could share your error messages when installing the packages. Then I can help you install the packages and fix the issue if it is a problem on our side.
