### ISSUE TITLE
About min-cut

### ISSUE THREAD

**Issue by wutaiqiang** [snap-research/graphless-neural-networks#9]
hello, I try to re-run citeseer under transduction setting.
The seeds are 1 2 3 4 5.

I get an average of 71.22, proving the correctness of my experiments.

however, for min-cut: I get 
0.7159
0.6828
0.7444
0.9163
0.5613

It is highly unstable.

Meanwhile, for GLNN, I get:
0.9457
0.9499
0.9519
0.9670
0.9278

So maybe the min-cut just work for GLNN well and fail to capture the graph topology

**Comment by ShichangZh** [comment]
Thank you for reaching out. Just to confirm the question here. Are you saying that the first five numbers are the results you get when you apply the min-cut loss to a GNN model? Did you use GraphSAGE, or did you use other architectures?

**Comment by wutaiqiang** [comment]
Yes   sage as teacherAlso i try other teacher，and it is unstable tooHowever for student from glnn， it is high and stable I think my experiment setting is okay since my distillation results are right and near the report results-------- 原始邮件 --------发件人： Shichang Zhang ***@***.***>日期： 2023年3月14日周二 早上8:07收件人： snap-research/graphless-neural-networks ***@***.***>抄送： wutaiqiang ***@***.***>, Author ***@***.***>主    题： Re: [snap-research/graphless-neural-networks] About min-cut (Issue #9)
Thank you for reaching out. Just to confirm the question here. Are you saying that the first five numbers are the results you get when you apply the min-cut loss to a GNN model? Did you use GraphSAGE, or did you use other architectures?

**Comment by ShichangZh** [comment]
I see. It is been a while, so I will have to go back and check our code again, which may take some time. Meanwhile, may I ask did you only observe this for Citeseer or other datasets as well? Could you please also provide results on a few more datasets if you have them? Say Cora.

By the way, your previous comment is messed up with some extra email information. You may want to edit it.

**Comment by wutaiqiang** [comment]
After my doubt check, I find I get such results due to:

I forget to softmax the results for teacher, but I do that for student.

Hence, results from teacher are unstable but from student are not so .

After fix the issue, I get:

teacher:
0.9904
0.9978
0.9898
0.9957
0.9925

student:
0.9457
0.9499
0.9519
0.9670
0.9278

setting: SAGE, Citeseer, and transductive.
